### ISSUE TITLE
File \AsciiShape\Win32\Release\asciishapeeditor.exe is cosidered to be Virus

### ISSUE THREAD

**Issue by TommiPrami** [tothpaul/Delphi#1]
Below is report from the VirusTotal, added all virus scanners detected something fishy (Or think so)

Is distributing the Binary necessary at the Repository it self. Maybe separate download would be better in anyways.

Ad-Aware              Trojan.GenericKD.4921127
AhnLab-V3             Trojan/Win32.Scar.C1594560
ALYac                 Trojan.GenericKD.4921127
Arcabit               Trojan.Generic.D4B1727
Avira                 ADWARE/Agent.btuqu
AVware                Trojan.Win32.Generic!BT
BitDefender           Trojan.GenericKD.4921127
CAT-QuickHeal         Heur.Adware
Emsisoft              Trojan.GenericKD.4921127 (B)
Endgame               malicious (high confidence)
eScan                 Trojan.GenericKD.4921127
F-Secure              Trojan.GenericKD.4921127
Fortinet              Adware/Generic
GData                 Trojan.GenericKD.4921127
Kaspersky             not-a-virus:HEUR:AdWare.Win32.Generic
Panda                 Trj/GdSda.A
Qihoo-360             Win32/Virus.Adware.b51
Rising                Malware.Undefined!8.C (cloud:Vqnlvfk2J5S)
Symantec              Trojan.Gen
TrendMicro            TROJ_GEN.R0ADC0VDS17
TrendMicro-HouseCall  TROJ_GEN.R0ADC0VDS17
VIPRE                 Trojan.Win32.Generic!BT
ZoneAlarm             not-a-virus:HEUR:AdWare.Win32.Generic

**Comment by tothpaul** [comment]
there's no virus is this file.

**Comment by TommiPrami** [comment]
I know.

Sent the false positive announcement to our Antivirus vendor and got rid of personal problem.

Seems that something in the exe makes many of the Virus scanners heuristics to jump. Maybe some piece of code that is made with delphi in some malware.

-Tee-
