### ISSUE TITLE
Can it be used for SMTP?

### ISSUE THREAD

**Issue by Smidesang** [tothpaul/Delphi#12]
Hi, I cannot get it to work with smtp.office365.com.
The error I get after about 10 seconds is "Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully."

My settings used to work using OpenSSL, but that stopped working tuesday 30th juli 2024 for no apparent reason.

Now I have just created a TIdSSLIOHandlerSocketSChannel and set TIdSMTP.IOHandler to point to it.
Are there other properties to set, or code to initialize?

**Comment by tothpaul** [comment]
Hi,

I didn't try with SMTP, but I know that Outlook has changed the sign-on process. You now have to use OAuth2, even with Thunderbird.
