### ISSUE TITLE
Indy.SChannel with my link

### ISSUE THREAD

**Issue by limelect** [tothpaul/Delphi#13]
Using your demo in Indy.SChannel
I have this link to my provider server
https://limelect.com/UpDate/document-projects.txt
Protocol error
I could not find a way to find the protocol version

![Screenshot - 21_10_2024 , 10_13_39](https://github.com/user-attachments/assets/79b0fc60-4bb5-4faa-a488-210e9c25f2a7)

**Comment by tothpaul** [comment]
Hi,

this is an OpenSSL error, not a SChannel one :)

in fact, my SChannel implementation is a way to use TLS 1.3 with Delphi WITHOUT  OpenSSL ;)

click on the SChannel Button and you'll have the "1.0.0.6" response.
