### ISSUE TITLE
Indy.SChannel with my link

### ISSUE THREAD

**Issue by limelect** [tothpaul/Delphi#14]
I reopen the problem
Sorry paul pressing SCbutton on this link gives me initializing error
https://limelect.com/UpDate/document-projects.txt
![Screenshot - 25_10_2024 , 09_55_29](https://github.com/user-attachments/assets/f87e51e1-57cf-4bdf-a8bf-a5fcc11c8110)

P,S This error got after my provider updated his server, Before your lib worked without any problems

**Comment by tothpaul** [comment]
I don't have this error...and it is a strange error, while verifying the server certificate with SEC_E_INVALID_HANDLE

can you read this URL from a webbrowser on the same PC ? have you an old version of Windows ?

I don't see any good reason for that...or perhaps a Firewall problem ?

**Comment by limelect** [comment]
Yes no problem reading Txt file with Chrome
Using window 7 but I doubt that this is the problem
I will try to use this with window 11

**Comment by limelect** [comment]
OK I checked with window 11 and I do get 1.0.0.6
Do you have any Idea what is going on? Why?

**Comment by tothpaul** [comment]
can you disable the firewall ?

I don't see any good reason, sorry

**Comment by limelect** [comment]
Thanks
