### ISSUE TITLE
[IndySchannel] Socks TransparentProxy throws Exception

### ISSUE THREAD

**Issue by silverqx** [tothpaul/Delphi#4]
I'm trying to use your schannel implementation with Indy, it works great, until I assign `TIdSocksInfo` to `TIdSSLIOHandlerSocketSChannel.TransparentProxy`, in this case I get an exception -> access violation at 0xXXX: read of address 0xXXX.

I little debugged what is happening and the problem occurs at `TIdSSLIOHandlerSocketBase.WriteDataToTarget` because `PassThrough` is `False`, when I execute the same example with `TIdSSLIOHandlerSocketOpenSSL`, so `PassThrough` is `True`.

So somewhere before `PassThrough` is not initialized correctly.

Example code is simple:
```
  LMem := TStringStream.Create;

  LSchannel := TIdSSLIOHandlerSocketSChannel.Create;
  LSchannel.TransparentProxy := IdSocksInfo1;
  IdHTTP1.IOHandler := LSchannel;

// for openssl
//  LOpenSsl := TIdSSLIOHandlerSocketOpenSSL.Create;
//  LOpenSsl.TransparentProxy := IdSocksInfo1;
//  IdHTTP1.IOHandler := LOpenSsl;

  IdHTTP1.Get(
    'https://check.torproject.org/api/ip',
    LMem
  );

  LMem.Free;
  FreeAndNil(LOSssl);
  FreeAndNil(LSchannel);
```

**Comment by tothpaul** [comment]
You're probably right, but I don't know what this TransparentProxy option is for :)

for Proxy I use TidHTTP.ProxyParams, is that an other way to do things or a different option ?

Unforunatly TIdSSLIOHandlerSocketBase do not handle all what it should, probably because Indy supports only OpenSSL AFAIK...my code do not set PassThrough it just test it state.

**Comment by silverqx** [comment]
`TransparentProxy` is for SOCKS proxies, the only thing which you can assign to this property is `TIdSocksInfo` instance, where you configure SOCKS proxy.
SOCKS proxies are another type of proxies.
`TidHTTP.ProxyParams` are for HTTP and HTTPs proxies.
eg **tor** creates socks proxy server which listens on 9050 or 9150 port, through which you can connect to the tor network.

**Comment by tothpaul** [comment]
Ok, but I don't have the time to look at that for now...you can look for the differences with the OpenSSL implementation, it can be a simple thing to fix... or not :D

Regards
Paul

**Comment by silverqx** [comment]
> it can be a simple thing to fix... or not :D

I think more likely that - or not 😂, but I maybe will need it, in that case, I fix it, will see
