### ISSUE TITLE
Pointer and THandle passed as Integer

### ISSUE THREAD

**Issue by JustGreatSoftware** [tothpaul/Delphi#7]
In Execute.SChannel.pas you have several functions like SSLRead that take an SSL parameter that is declared as Integer and then typecasted to a pointer type PSSLInfo.  In Execute.IdSSLSChannel.pas you are passing a variable declared as THandle as this parameter.  This looks incorrect to me.  On 64-bit Windows, THandle and Pointer are 64-bit, but Integer is 32-bit.  I'd expect the pointer to be passed incorrectly when the application uses more than 4 GB of RAM or when MEM_TOP_DOWN is enabled.  If the SSL parameter is really a pointer, why not just use the Pointer type?

**Comment by tothpaul** [comment]
You're right !

In fact, I don't use this unit on a 64bits project, so I didn't found this bug.

It should be a THandle...it could be a Pointer also given the implementation, but that makes an assemption about the data type, while THandle can be anything (like and index in a private list)

Thank you for the feedback
